# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gap/MyCode/SpaceInvaders

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gap/MyCode/SpaceInvaders

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gap/MyCode/SpaceInvaders/CMakeFiles /Users/gap/MyCode/SpaceInvaders//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gap/MyCode/SpaceInvaders/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SpaceInvaders

# Build rule for target.
SpaceInvaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SpaceInvaders
.PHONY : SpaceInvaders

# fast build rule for target.
SpaceInvaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/build
.PHONY : SpaceInvaders/fast

Actor.o: Actor.cpp.o
.PHONY : Actor.o

# target to build an object file
Actor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Actor.cpp.o
.PHONY : Actor.cpp.o

Actor.i: Actor.cpp.i
.PHONY : Actor.i

# target to preprocess a source file
Actor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Actor.cpp.i
.PHONY : Actor.cpp.i

Actor.s: Actor.cpp.s
.PHONY : Actor.s

# target to generate assembly for a file
Actor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Actor.cpp.s
.PHONY : Actor.cpp.s

ActorManager.o: ActorManager.cpp.o
.PHONY : ActorManager.o

# target to build an object file
ActorManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ActorManager.cpp.o
.PHONY : ActorManager.cpp.o

ActorManager.i: ActorManager.cpp.i
.PHONY : ActorManager.i

# target to preprocess a source file
ActorManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ActorManager.cpp.i
.PHONY : ActorManager.cpp.i

ActorManager.s: ActorManager.cpp.s
.PHONY : ActorManager.s

# target to generate assembly for a file
ActorManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ActorManager.cpp.s
.PHONY : ActorManager.cpp.s

Controller.o: Controller.cpp.o
.PHONY : Controller.o

# target to build an object file
Controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Controller.cpp.o
.PHONY : Controller.cpp.o

Controller.i: Controller.cpp.i
.PHONY : Controller.i

# target to preprocess a source file
Controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Controller.cpp.i
.PHONY : Controller.cpp.i

Controller.s: Controller.cpp.s
.PHONY : Controller.s

# target to generate assembly for a file
Controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Controller.cpp.s
.PHONY : Controller.cpp.s

Engine.o: Engine.cpp.o
.PHONY : Engine.o

# target to build an object file
Engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Engine.cpp.o
.PHONY : Engine.cpp.o

Engine.i: Engine.cpp.i
.PHONY : Engine.i

# target to preprocess a source file
Engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Engine.cpp.i
.PHONY : Engine.cpp.i

Engine.s: Engine.cpp.s
.PHONY : Engine.s

# target to generate assembly for a file
Engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Engine.cpp.s
.PHONY : Engine.cpp.s

Grid.o: Grid.cpp.o
.PHONY : Grid.o

# target to build an object file
Grid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Grid.cpp.o
.PHONY : Grid.cpp.o

Grid.i: Grid.cpp.i
.PHONY : Grid.i

# target to preprocess a source file
Grid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Grid.cpp.i
.PHONY : Grid.cpp.i

Grid.s: Grid.cpp.s
.PHONY : Grid.s

# target to generate assembly for a file
Grid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Grid.cpp.s
.PHONY : Grid.cpp.s

LevelManager.o: LevelManager.cpp.o
.PHONY : LevelManager.o

# target to build an object file
LevelManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/LevelManager.cpp.o
.PHONY : LevelManager.cpp.o

LevelManager.i: LevelManager.cpp.i
.PHONY : LevelManager.i

# target to preprocess a source file
LevelManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/LevelManager.cpp.i
.PHONY : LevelManager.cpp.i

LevelManager.s: LevelManager.cpp.s
.PHONY : LevelManager.s

# target to generate assembly for a file
LevelManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/LevelManager.cpp.s
.PHONY : LevelManager.cpp.s

Particle.o: Particle.cpp.o
.PHONY : Particle.o

# target to build an object file
Particle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Particle.cpp.o
.PHONY : Particle.cpp.o

Particle.i: Particle.cpp.i
.PHONY : Particle.i

# target to preprocess a source file
Particle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Particle.cpp.i
.PHONY : Particle.cpp.i

Particle.s: Particle.cpp.s
.PHONY : Particle.s

# target to generate assembly for a file
Particle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Particle.cpp.s
.PHONY : Particle.cpp.s

ParticleSystem.o: ParticleSystem.cpp.o
.PHONY : ParticleSystem.o

# target to build an object file
ParticleSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ParticleSystem.cpp.o
.PHONY : ParticleSystem.cpp.o

ParticleSystem.i: ParticleSystem.cpp.i
.PHONY : ParticleSystem.i

# target to preprocess a source file
ParticleSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ParticleSystem.cpp.i
.PHONY : ParticleSystem.cpp.i

ParticleSystem.s: ParticleSystem.cpp.s
.PHONY : ParticleSystem.s

# target to generate assembly for a file
ParticleSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/ParticleSystem.cpp.s
.PHONY : ParticleSystem.cpp.s

SoundManager.o: SoundManager.cpp.o
.PHONY : SoundManager.o

# target to build an object file
SoundManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SoundManager.cpp.o
.PHONY : SoundManager.cpp.o

SoundManager.i: SoundManager.cpp.i
.PHONY : SoundManager.i

# target to preprocess a source file
SoundManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SoundManager.cpp.i
.PHONY : SoundManager.cpp.i

SoundManager.s: SoundManager.cpp.s
.PHONY : SoundManager.s

# target to generate assembly for a file
SoundManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SoundManager.cpp.s
.PHONY : SoundManager.cpp.s

SpaceInvaders.o: SpaceInvaders.cpp.o
.PHONY : SpaceInvaders.o

# target to build an object file
SpaceInvaders.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders.cpp.o
.PHONY : SpaceInvaders.cpp.o

SpaceInvaders.i: SpaceInvaders.cpp.i
.PHONY : SpaceInvaders.i

# target to preprocess a source file
SpaceInvaders.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders.cpp.i
.PHONY : SpaceInvaders.cpp.i

SpaceInvaders.s: SpaceInvaders.cpp.s
.PHONY : SpaceInvaders.s

# target to generate assembly for a file
SpaceInvaders.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpaceInvaders.cpp.s
.PHONY : SpaceInvaders.cpp.s

SpriteSheet.o: SpriteSheet.cpp.o
.PHONY : SpriteSheet.o

# target to build an object file
SpriteSheet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpriteSheet.cpp.o
.PHONY : SpriteSheet.cpp.o

SpriteSheet.i: SpriteSheet.cpp.i
.PHONY : SpriteSheet.i

# target to preprocess a source file
SpriteSheet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpriteSheet.cpp.i
.PHONY : SpriteSheet.cpp.i

SpriteSheet.s: SpriteSheet.cpp.s
.PHONY : SpriteSheet.s

# target to generate assembly for a file
SpriteSheet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SpriteSheet.cpp.s
.PHONY : SpriteSheet.cpp.s

StateManager.o: StateManager.cpp.o
.PHONY : StateManager.o

# target to build an object file
StateManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/StateManager.cpp.o
.PHONY : StateManager.cpp.o

StateManager.i: StateManager.cpp.i
.PHONY : StateManager.i

# target to preprocess a source file
StateManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/StateManager.cpp.i
.PHONY : StateManager.cpp.i

StateManager.s: StateManager.cpp.s
.PHONY : StateManager.s

# target to generate assembly for a file
StateManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/StateManager.cpp.s
.PHONY : StateManager.cpp.s

State_Game.o: State_Game.cpp.o
.PHONY : State_Game.o

# target to build an object file
State_Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Game.cpp.o
.PHONY : State_Game.cpp.o

State_Game.i: State_Game.cpp.i
.PHONY : State_Game.i

# target to preprocess a source file
State_Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Game.cpp.i
.PHONY : State_Game.cpp.i

State_Game.s: State_Game.cpp.s
.PHONY : State_Game.s

# target to generate assembly for a file
State_Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Game.cpp.s
.PHONY : State_Game.cpp.s

State_GameOver.o: State_GameOver.cpp.o
.PHONY : State_GameOver.o

# target to build an object file
State_GameOver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_GameOver.cpp.o
.PHONY : State_GameOver.cpp.o

State_GameOver.i: State_GameOver.cpp.i
.PHONY : State_GameOver.i

# target to preprocess a source file
State_GameOver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_GameOver.cpp.i
.PHONY : State_GameOver.cpp.i

State_GameOver.s: State_GameOver.cpp.s
.PHONY : State_GameOver.s

# target to generate assembly for a file
State_GameOver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_GameOver.cpp.s
.PHONY : State_GameOver.cpp.s

State_Intro.o: State_Intro.cpp.o
.PHONY : State_Intro.o

# target to build an object file
State_Intro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Intro.cpp.o
.PHONY : State_Intro.cpp.o

State_Intro.i: State_Intro.cpp.i
.PHONY : State_Intro.i

# target to preprocess a source file
State_Intro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Intro.cpp.i
.PHONY : State_Intro.cpp.i

State_Intro.s: State_Intro.cpp.s
.PHONY : State_Intro.s

# target to generate assembly for a file
State_Intro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Intro.cpp.s
.PHONY : State_Intro.cpp.s

State_Paused.o: State_Paused.cpp.o
.PHONY : State_Paused.o

# target to build an object file
State_Paused.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Paused.cpp.o
.PHONY : State_Paused.cpp.o

State_Paused.i: State_Paused.cpp.i
.PHONY : State_Paused.i

# target to preprocess a source file
State_Paused.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Paused.cpp.i
.PHONY : State_Paused.cpp.i

State_Paused.s: State_Paused.cpp.s
.PHONY : State_Paused.s

# target to generate assembly for a file
State_Paused.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/State_Paused.cpp.s
.PHONY : State_Paused.cpp.s

Sys.o: Sys.cpp.o
.PHONY : Sys.o

# target to build an object file
Sys.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys.cpp.o
.PHONY : Sys.cpp.o

Sys.i: Sys.cpp.i
.PHONY : Sys.i

# target to preprocess a source file
Sys.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys.cpp.i
.PHONY : Sys.cpp.i

Sys.s: Sys.cpp.s
.PHONY : Sys.s

# target to generate assembly for a file
Sys.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys.cpp.s
.PHONY : Sys.cpp.s

SysManager.o: SysManager.cpp.o
.PHONY : SysManager.o

# target to build an object file
SysManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SysManager.cpp.o
.PHONY : SysManager.cpp.o

SysManager.i: SysManager.cpp.i
.PHONY : SysManager.i

# target to preprocess a source file
SysManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SysManager.cpp.i
.PHONY : SysManager.cpp.i

SysManager.s: SysManager.cpp.s
.PHONY : SysManager.s

# target to generate assembly for a file
SysManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/SysManager.cpp.s
.PHONY : SysManager.cpp.s

Sys_BulletControl.o: Sys_BulletControl.cpp.o
.PHONY : Sys_BulletControl.o

# target to build an object file
Sys_BulletControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BulletControl.cpp.o
.PHONY : Sys_BulletControl.cpp.o

Sys_BulletControl.i: Sys_BulletControl.cpp.i
.PHONY : Sys_BulletControl.i

# target to preprocess a source file
Sys_BulletControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BulletControl.cpp.i
.PHONY : Sys_BulletControl.cpp.i

Sys_BulletControl.s: Sys_BulletControl.cpp.s
.PHONY : Sys_BulletControl.s

# target to generate assembly for a file
Sys_BulletControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BulletControl.cpp.s
.PHONY : Sys_BulletControl.cpp.s

Sys_BunkerControl.o: Sys_BunkerControl.cpp.o
.PHONY : Sys_BunkerControl.o

# target to build an object file
Sys_BunkerControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BunkerControl.cpp.o
.PHONY : Sys_BunkerControl.cpp.o

Sys_BunkerControl.i: Sys_BunkerControl.cpp.i
.PHONY : Sys_BunkerControl.i

# target to preprocess a source file
Sys_BunkerControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BunkerControl.cpp.i
.PHONY : Sys_BunkerControl.cpp.i

Sys_BunkerControl.s: Sys_BunkerControl.cpp.s
.PHONY : Sys_BunkerControl.s

# target to generate assembly for a file
Sys_BunkerControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_BunkerControl.cpp.s
.PHONY : Sys_BunkerControl.cpp.s

Sys_Collision.o: Sys_Collision.cpp.o
.PHONY : Sys_Collision.o

# target to build an object file
Sys_Collision.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Collision.cpp.o
.PHONY : Sys_Collision.cpp.o

Sys_Collision.i: Sys_Collision.cpp.i
.PHONY : Sys_Collision.i

# target to preprocess a source file
Sys_Collision.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Collision.cpp.i
.PHONY : Sys_Collision.cpp.i

Sys_Collision.s: Sys_Collision.cpp.s
.PHONY : Sys_Collision.s

# target to generate assembly for a file
Sys_Collision.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Collision.cpp.s
.PHONY : Sys_Collision.cpp.s

Sys_Gravity.o: Sys_Gravity.cpp.o
.PHONY : Sys_Gravity.o

# target to build an object file
Sys_Gravity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Gravity.cpp.o
.PHONY : Sys_Gravity.cpp.o

Sys_Gravity.i: Sys_Gravity.cpp.i
.PHONY : Sys_Gravity.i

# target to preprocess a source file
Sys_Gravity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Gravity.cpp.i
.PHONY : Sys_Gravity.cpp.i

Sys_Gravity.s: Sys_Gravity.cpp.s
.PHONY : Sys_Gravity.s

# target to generate assembly for a file
Sys_Gravity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Gravity.cpp.s
.PHONY : Sys_Gravity.cpp.s

Sys_Health.o: Sys_Health.cpp.o
.PHONY : Sys_Health.o

# target to build an object file
Sys_Health.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Health.cpp.o
.PHONY : Sys_Health.cpp.o

Sys_Health.i: Sys_Health.cpp.i
.PHONY : Sys_Health.i

# target to preprocess a source file
Sys_Health.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Health.cpp.i
.PHONY : Sys_Health.cpp.i

Sys_Health.s: Sys_Health.cpp.s
.PHONY : Sys_Health.s

# target to generate assembly for a file
Sys_Health.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Health.cpp.s
.PHONY : Sys_Health.cpp.s

Sys_InvaderControl.o: Sys_InvaderControl.cpp.o
.PHONY : Sys_InvaderControl.o

# target to build an object file
Sys_InvaderControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_InvaderControl.cpp.o
.PHONY : Sys_InvaderControl.cpp.o

Sys_InvaderControl.i: Sys_InvaderControl.cpp.i
.PHONY : Sys_InvaderControl.i

# target to preprocess a source file
Sys_InvaderControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_InvaderControl.cpp.i
.PHONY : Sys_InvaderControl.cpp.i

Sys_InvaderControl.s: Sys_InvaderControl.cpp.s
.PHONY : Sys_InvaderControl.s

# target to generate assembly for a file
Sys_InvaderControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_InvaderControl.cpp.s
.PHONY : Sys_InvaderControl.cpp.s

Sys_LevelState.o: Sys_LevelState.cpp.o
.PHONY : Sys_LevelState.o

# target to build an object file
Sys_LevelState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_LevelState.cpp.o
.PHONY : Sys_LevelState.cpp.o

Sys_LevelState.i: Sys_LevelState.cpp.i
.PHONY : Sys_LevelState.i

# target to preprocess a source file
Sys_LevelState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_LevelState.cpp.i
.PHONY : Sys_LevelState.cpp.i

Sys_LevelState.s: Sys_LevelState.cpp.s
.PHONY : Sys_LevelState.s

# target to generate assembly for a file
Sys_LevelState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_LevelState.cpp.s
.PHONY : Sys_LevelState.cpp.s

Sys_Movement.o: Sys_Movement.cpp.o
.PHONY : Sys_Movement.o

# target to build an object file
Sys_Movement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Movement.cpp.o
.PHONY : Sys_Movement.cpp.o

Sys_Movement.i: Sys_Movement.cpp.i
.PHONY : Sys_Movement.i

# target to preprocess a source file
Sys_Movement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Movement.cpp.i
.PHONY : Sys_Movement.cpp.i

Sys_Movement.s: Sys_Movement.cpp.s
.PHONY : Sys_Movement.s

# target to generate assembly for a file
Sys_Movement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Movement.cpp.s
.PHONY : Sys_Movement.cpp.s

Sys_PlayerControl.o: Sys_PlayerControl.cpp.o
.PHONY : Sys_PlayerControl.o

# target to build an object file
Sys_PlayerControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_PlayerControl.cpp.o
.PHONY : Sys_PlayerControl.cpp.o

Sys_PlayerControl.i: Sys_PlayerControl.cpp.i
.PHONY : Sys_PlayerControl.i

# target to preprocess a source file
Sys_PlayerControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_PlayerControl.cpp.i
.PHONY : Sys_PlayerControl.cpp.i

Sys_PlayerControl.s: Sys_PlayerControl.cpp.s
.PHONY : Sys_PlayerControl.s

# target to generate assembly for a file
Sys_PlayerControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_PlayerControl.cpp.s
.PHONY : Sys_PlayerControl.cpp.s

Sys_Renderer.o: Sys_Renderer.cpp.o
.PHONY : Sys_Renderer.o

# target to build an object file
Sys_Renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Renderer.cpp.o
.PHONY : Sys_Renderer.cpp.o

Sys_Renderer.i: Sys_Renderer.cpp.i
.PHONY : Sys_Renderer.i

# target to preprocess a source file
Sys_Renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Renderer.cpp.i
.PHONY : Sys_Renderer.cpp.i

Sys_Renderer.s: Sys_Renderer.cpp.s
.PHONY : Sys_Renderer.s

# target to generate assembly for a file
Sys_Renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Renderer.cpp.s
.PHONY : Sys_Renderer.cpp.s

Sys_Rotation.o: Sys_Rotation.cpp.o
.PHONY : Sys_Rotation.o

# target to build an object file
Sys_Rotation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Rotation.cpp.o
.PHONY : Sys_Rotation.cpp.o

Sys_Rotation.i: Sys_Rotation.cpp.i
.PHONY : Sys_Rotation.i

# target to preprocess a source file
Sys_Rotation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Rotation.cpp.i
.PHONY : Sys_Rotation.cpp.i

Sys_Rotation.s: Sys_Rotation.cpp.s
.PHONY : Sys_Rotation.s

# target to generate assembly for a file
Sys_Rotation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Rotation.cpp.s
.PHONY : Sys_Rotation.cpp.s

Sys_ShipSway.o: Sys_ShipSway.cpp.o
.PHONY : Sys_ShipSway.o

# target to build an object file
Sys_ShipSway.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShipSway.cpp.o
.PHONY : Sys_ShipSway.cpp.o

Sys_ShipSway.i: Sys_ShipSway.cpp.i
.PHONY : Sys_ShipSway.i

# target to preprocess a source file
Sys_ShipSway.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShipSway.cpp.i
.PHONY : Sys_ShipSway.cpp.i

Sys_ShipSway.s: Sys_ShipSway.cpp.s
.PHONY : Sys_ShipSway.s

# target to generate assembly for a file
Sys_ShipSway.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShipSway.cpp.s
.PHONY : Sys_ShipSway.cpp.s

Sys_ShockwaveControl.o: Sys_ShockwaveControl.cpp.o
.PHONY : Sys_ShockwaveControl.o

# target to build an object file
Sys_ShockwaveControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShockwaveControl.cpp.o
.PHONY : Sys_ShockwaveControl.cpp.o

Sys_ShockwaveControl.i: Sys_ShockwaveControl.cpp.i
.PHONY : Sys_ShockwaveControl.i

# target to preprocess a source file
Sys_ShockwaveControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShockwaveControl.cpp.i
.PHONY : Sys_ShockwaveControl.cpp.i

Sys_ShockwaveControl.s: Sys_ShockwaveControl.cpp.s
.PHONY : Sys_ShockwaveControl.s

# target to generate assembly for a file
Sys_ShockwaveControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_ShockwaveControl.cpp.s
.PHONY : Sys_ShockwaveControl.cpp.s

Sys_Sound.o: Sys_Sound.cpp.o
.PHONY : Sys_Sound.o

# target to build an object file
Sys_Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Sound.cpp.o
.PHONY : Sys_Sound.cpp.o

Sys_Sound.i: Sys_Sound.cpp.i
.PHONY : Sys_Sound.i

# target to preprocess a source file
Sys_Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Sound.cpp.i
.PHONY : Sys_Sound.cpp.i

Sys_Sound.s: Sys_Sound.cpp.s
.PHONY : Sys_Sound.s

# target to generate assembly for a file
Sys_Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Sound.cpp.s
.PHONY : Sys_Sound.cpp.s

Sys_Spring.o: Sys_Spring.cpp.o
.PHONY : Sys_Spring.o

# target to build an object file
Sys_Spring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Spring.cpp.o
.PHONY : Sys_Spring.cpp.o

Sys_Spring.i: Sys_Spring.cpp.i
.PHONY : Sys_Spring.i

# target to preprocess a source file
Sys_Spring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Spring.cpp.i
.PHONY : Sys_Spring.cpp.i

Sys_Spring.s: Sys_Spring.cpp.s
.PHONY : Sys_Spring.s

# target to generate assembly for a file
Sys_Spring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_Spring.cpp.s
.PHONY : Sys_Spring.cpp.s

Sys_TorqueSpring.o: Sys_TorqueSpring.cpp.o
.PHONY : Sys_TorqueSpring.o

# target to build an object file
Sys_TorqueSpring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_TorqueSpring.cpp.o
.PHONY : Sys_TorqueSpring.cpp.o

Sys_TorqueSpring.i: Sys_TorqueSpring.cpp.i
.PHONY : Sys_TorqueSpring.i

# target to preprocess a source file
Sys_TorqueSpring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_TorqueSpring.cpp.i
.PHONY : Sys_TorqueSpring.cpp.i

Sys_TorqueSpring.s: Sys_TorqueSpring.cpp.s
.PHONY : Sys_TorqueSpring.s

# target to generate assembly for a file
Sys_TorqueSpring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_TorqueSpring.cpp.s
.PHONY : Sys_TorqueSpring.cpp.s

Sys_UFOControl.o: Sys_UFOControl.cpp.o
.PHONY : Sys_UFOControl.o

# target to build an object file
Sys_UFOControl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_UFOControl.cpp.o
.PHONY : Sys_UFOControl.cpp.o

Sys_UFOControl.i: Sys_UFOControl.cpp.i
.PHONY : Sys_UFOControl.i

# target to preprocess a source file
Sys_UFOControl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_UFOControl.cpp.i
.PHONY : Sys_UFOControl.cpp.i

Sys_UFOControl.s: Sys_UFOControl.cpp.s
.PHONY : Sys_UFOControl.s

# target to generate assembly for a file
Sys_UFOControl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/Sys_UFOControl.cpp.s
.PHONY : Sys_UFOControl.cpp.s

WindowManager.o: WindowManager.cpp.o
.PHONY : WindowManager.o

# target to build an object file
WindowManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/WindowManager.cpp.o
.PHONY : WindowManager.cpp.o

WindowManager.i: WindowManager.cpp.i
.PHONY : WindowManager.i

# target to preprocess a source file
WindowManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/WindowManager.cpp.i
.PHONY : WindowManager.cpp.i

WindowManager.s: WindowManager.cpp.s
.PHONY : WindowManager.s

# target to generate assembly for a file
WindowManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SpaceInvaders.dir/build.make CMakeFiles/SpaceInvaders.dir/WindowManager.cpp.s
.PHONY : WindowManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SpaceInvaders"
	@echo "... Actor.o"
	@echo "... Actor.i"
	@echo "... Actor.s"
	@echo "... ActorManager.o"
	@echo "... ActorManager.i"
	@echo "... ActorManager.s"
	@echo "... Controller.o"
	@echo "... Controller.i"
	@echo "... Controller.s"
	@echo "... Engine.o"
	@echo "... Engine.i"
	@echo "... Engine.s"
	@echo "... Grid.o"
	@echo "... Grid.i"
	@echo "... Grid.s"
	@echo "... LevelManager.o"
	@echo "... LevelManager.i"
	@echo "... LevelManager.s"
	@echo "... Particle.o"
	@echo "... Particle.i"
	@echo "... Particle.s"
	@echo "... ParticleSystem.o"
	@echo "... ParticleSystem.i"
	@echo "... ParticleSystem.s"
	@echo "... SoundManager.o"
	@echo "... SoundManager.i"
	@echo "... SoundManager.s"
	@echo "... SpaceInvaders.o"
	@echo "... SpaceInvaders.i"
	@echo "... SpaceInvaders.s"
	@echo "... SpriteSheet.o"
	@echo "... SpriteSheet.i"
	@echo "... SpriteSheet.s"
	@echo "... StateManager.o"
	@echo "... StateManager.i"
	@echo "... StateManager.s"
	@echo "... State_Game.o"
	@echo "... State_Game.i"
	@echo "... State_Game.s"
	@echo "... State_GameOver.o"
	@echo "... State_GameOver.i"
	@echo "... State_GameOver.s"
	@echo "... State_Intro.o"
	@echo "... State_Intro.i"
	@echo "... State_Intro.s"
	@echo "... State_Paused.o"
	@echo "... State_Paused.i"
	@echo "... State_Paused.s"
	@echo "... Sys.o"
	@echo "... Sys.i"
	@echo "... Sys.s"
	@echo "... SysManager.o"
	@echo "... SysManager.i"
	@echo "... SysManager.s"
	@echo "... Sys_BulletControl.o"
	@echo "... Sys_BulletControl.i"
	@echo "... Sys_BulletControl.s"
	@echo "... Sys_BunkerControl.o"
	@echo "... Sys_BunkerControl.i"
	@echo "... Sys_BunkerControl.s"
	@echo "... Sys_Collision.o"
	@echo "... Sys_Collision.i"
	@echo "... Sys_Collision.s"
	@echo "... Sys_Gravity.o"
	@echo "... Sys_Gravity.i"
	@echo "... Sys_Gravity.s"
	@echo "... Sys_Health.o"
	@echo "... Sys_Health.i"
	@echo "... Sys_Health.s"
	@echo "... Sys_InvaderControl.o"
	@echo "... Sys_InvaderControl.i"
	@echo "... Sys_InvaderControl.s"
	@echo "... Sys_LevelState.o"
	@echo "... Sys_LevelState.i"
	@echo "... Sys_LevelState.s"
	@echo "... Sys_Movement.o"
	@echo "... Sys_Movement.i"
	@echo "... Sys_Movement.s"
	@echo "... Sys_PlayerControl.o"
	@echo "... Sys_PlayerControl.i"
	@echo "... Sys_PlayerControl.s"
	@echo "... Sys_Renderer.o"
	@echo "... Sys_Renderer.i"
	@echo "... Sys_Renderer.s"
	@echo "... Sys_Rotation.o"
	@echo "... Sys_Rotation.i"
	@echo "... Sys_Rotation.s"
	@echo "... Sys_ShipSway.o"
	@echo "... Sys_ShipSway.i"
	@echo "... Sys_ShipSway.s"
	@echo "... Sys_ShockwaveControl.o"
	@echo "... Sys_ShockwaveControl.i"
	@echo "... Sys_ShockwaveControl.s"
	@echo "... Sys_Sound.o"
	@echo "... Sys_Sound.i"
	@echo "... Sys_Sound.s"
	@echo "... Sys_Spring.o"
	@echo "... Sys_Spring.i"
	@echo "... Sys_Spring.s"
	@echo "... Sys_TorqueSpring.o"
	@echo "... Sys_TorqueSpring.i"
	@echo "... Sys_TorqueSpring.s"
	@echo "... Sys_UFOControl.o"
	@echo "... Sys_UFOControl.i"
	@echo "... Sys_UFOControl.s"
	@echo "... WindowManager.o"
	@echo "... WindowManager.i"
	@echo "... WindowManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

